runner:
  total_steps: 10000
  gradient_clipping: 1
  gradient_accumulate_steps: 2

  log_step: 200
  eval_step: 200
  save_step: 4000
  max_keep: 2
  eval_dataloaders:
     - dev

  # debbugin
  #total_steps: 2
  #gradient_clipping: 1
  #gradient_accumulate_steps: 1

  #log_step: 1
  #eval_step: 1
  #save_step: 1
  #max_keep: 1
  #eval_dataloaders:
    #- dev
   # - test

optimizer:
  name: AdamW
  lr: 1.5e-4

downstream_expert:
  datarc:
    num_workers: 12
    train_batch_size: 32
    eval_batch_size: 64
    data_root: ./downstream/pronscor_classification/data_l2arctic/L2arctic
    phone_path: ./downstream/pronscor_classification/data_l2arctic
    #phone_list: 'pronscor_class/data/phones-list.txt'
    npc: False 
    # phone_weights: ./downstream/pronscor_classification/data_l2arctic/phone_weights_50.yaml
    bucket_file: ./downstream/pronscor_classification/data_l2arctic/len_for_bucket # run: `python preprocess/generate_len_for_bucket.py -i your_path_to/TIMIT -a .WAV -n len_for_bucket_timit`
    sample_rate: 16000 # this should not be changed, and this should match the sr of the audio in `libri_root`

  modelrc:
    select: ConvBank
    ConvBank:
      kernels: [3, 5, 7]
      cnn_size: 32
      hidden_size: 64
      dropout: 0.5
