runner:
  total_steps: 12000
  gradient_clipping: 1
  gradient_accumulate_steps: 2

  log_step: 600
  eval_step: 600
  save_step: 4000
  max_keep: 2
  eval_dataloaders:
     - dev

# scheduler:
#   name: cosine_schedule_with_warmup
#   num_warmup_steps: 200

  # debbugin
  #total_steps: 2
  #gradient_clipping: 1
  #gradient_accumulate_steps: 1

  #log_step: 1
  #eval_step: 1
  #save_step: 1
  #max_keep: 1
  #eval_dataloaders:
    #- dev
   # - test

# specaug:
#   apply_time_warp: true
#   apply_time_mask: true
#   apply_freq_mask: true
#   time_warp_window: 5
#   time_mask_width_range: [0, 40]
#   freq_mask_width_range: [0, 50]
#   num_freq_mask: 3
#   num_time_mask: 3

optimizer:
  name: AdamW
  lr: 1.0e-4

downstream_expert:
  datarc:
    num_workers: 12
    train_batch_size: 64
    bucketing: True
    eval_batch_size: 64
    data_root: ./downstream/pronscor_classification/data_l2arctic/L2arctic
    splits_path: ./downstream/pronscor_classification/data_l2arctic/splits_xval
    alignments_path: ./downstream/pronscor_classification/data_l2arctic/alignments_auto_label_manual_wzeros
    bucket_file: ./downstream/pronscor_classification/data_l2arctic/len_for_bucket # run: `python preprocess/generate_len_for_bucket.py -i your_path_to/TIMIT -a .WAV -n len_for_bucket_timit`
    sample_rate: 16000 # this should not be changed, and this should match the sr of the audio in `libri_root`

  modelrc:
    select: Linear
    Linear:
      {}